# Generated by Django 6.0.2 on 2026-02-21 13:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image of the food item', max_length=255, null=True, verbose_name='image'),
        ),
    ]
